### ISSUE TITLE
_sendMessage may have a possible silent failure

### ISSUE THREAD

**Issue by sjmcdowall** [flywheelsports/hydra#174]
Looking at the _sendMessage code .. I think we have a corner case condition where we can silently fail to send a message .. 

Use Case:  Invoke sendMessage with an invalid (or dead) specific instance ID . 

https://github.com/flywheelsports/hydra/blob/master/index.js#L1385

``` 

L1385          if (instance && instance !== '') {
            this._sendMessageThroughChannel(`${mcMessageKey}:${serviceName}:${instance}`, message);
          } else {
```

The code appears to blindly accept the instance given .. even if it is either totally bogus or not - running.  It seems to be there should be a check before the _sendMTC to see if the instance is actually in the array returned from _getServicePresence() and if not, invoke reject()

**Comment by cjus** [comment]
@sjmcdowall you are correct. The `instances` value here should be used to confirm an instance is available - if indeed the message in question directly references an instanceID in the UMF message `to` field.  Otherwise, any available instance should be used.

https://github.com/flywheelsports/hydra/blob/master/index.js#L1378

**Comment by sjmcdowall** [comment]
Fixed by https://github.com/flywheelsports/hydra/pull/182
